# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EventTracker
        pod 'PinLayout'
        pod 'Kingfisher'
        pod 'Firebase/Core'
        pod 'Firebase/Auth'
        pod 'Firebase/Database'

  target 'EventTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventTrackerUITests' do
    # Pods for testing
  end

end
